version: '3.4'

x-base-be-config: &be-config
  env_file: .env
  build:
    context: mock-backend
    dockerfile: docker/Dockerfile
  image: ${IMAGE_NAME_BE}
  depends_on: 
    - mongo-db
  network_mode: host

services:
  mock-backend-rest:
    <<: *be-config
    container_name: ${CONTAINER_NAME_BE_REST_API}
    ports:
      - ${API_REST_PORT}:${API_REST_PORT}
    command: ["python", "run_api_rest.py"]

  mock-backend-grpc:
    <<: *be-config
    container_name: ${CONTAINER_NAME_BE_GRPC}
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    command: ["python", "run_grpc_server.py"]

  mock-gql-gateway:
    network_mode: host
    env_file: .env
    build:
      context: mock-gateway
      dockerfile: docker/Dockerfile
    image: ${IMAGE_NAME_GQL}
    container_name: ${CONTAINER_NAME_GQL}
    ports:
      - ${GQL_PORT}:${GQL_PORT}
    depends_on:
      - mongo-db
    command: ["npm", "start"]


  mongo-db:
    env_file: .env
    build: 
      context: db_mock
    image: mongo_mock
    container_name: mongo_mock_container
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./db_mock/data:/data/db

  mock-ui:
    env_file: .env
    build:
      context: mock-ui
      dockerfile: Dockerfile
    image: ${IMAGE_NAME_UI}
    container_name: ${CONTAINER_NAME_UI}
    ports:
      - ${UI_PORT}:80
    depends_on:
      - mock-backend-rest
      - mock-backend-grpc
      - mock-gql-gateway
